# Site settings
title: Fullstack Developer 
header-img: img/home-bg.png
email: desmond.drakes@gmail.com
copyright_name: ddrakes
description: > # this means to ignore newlines until "baseurl:"
  Student 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ddrakes
learn_profile: ddrakes
email_username: desmond.drakes@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
